services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $generalLogger: '@monolog.logger.contao.general'
    
    InspiredMinds\ContaoNewsArchiving\:
        resource: ../src
